services:
  neo4j:
    image: neo4j:2025.10.1-community-bullseye
    container_name: neo4jdocker
    ports:
      - "7474:7474" # Neo4j HTTP
      - "7473:7473" # Neo4j HTTPS
      - "7687:7687" # Neo4j Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc", "bloom", "graph-data-science", "genai"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/import
      - ./plugins:/plugins